train_img_dir: 'hand_dataset/imgs/train'
train_keypoints_dir: 'hand_dataset/csv_21pts/train'
annotation_config: 'config/annotation/21pts.yml'
meta_architecture: 'ResidualStage3Net'
extractor: 'vgg16'
extractor_freeze: False
extract_layers: ['conv3_3']
# [`kernel size`, `output channels`, `padding`, `activ`]
# `activ` means activate function. r: relu, s: sigmoid, n: None, sr: sigmoid for residual.
estimator: [
            # Stage 1
            [[3, 128, 1, 'r'], [3, 128, 1, 'r'], [3, 128, 1, 'r'],
             [3, 128, 1, 'r'], [3, 128, 1, 'r'],
             [1, 512, 0, 'r'], [1, 21, 0, 'r']],
            # Stage 2
            [[7, 256, 3, 'r'], [7, 128, 3, 'r'], [7, 128, 3, 'r'],
             [7, 128, 3, 'r'], [7, 128, 3, 'r'],
             [1, 512, 0, 'r'], [1, 21, 0, 'sr']],
            # Stage 3
            [[7, 256, 3, 'r'], [7, 128, 3, 'r'], [7, 128, 3, 'r'],
             [7, 128, 3, 'r'], [7, 128, 3, 'r'],
             [1, 512, 0, 'r'], [1, 21, 0, 'sr']],
           ]
loss: 'GaussianWeightedMAE'
loss_w0: 0.001
loss_w1: 1
optimizer: 'SGD'
lr: 1  # learning rate
bs: 16  # batch size
epoch: 3000
step_save_model: 5  # unit is epoch
outpath_additional: '_ksize7'
